# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine AS build
WORKDIR /app

# Install dependencies
COPY package.json package-lock.json ./
RUN npm ci --ignore-scripts

# Copy source and build
COPY tsconfig.json ./
COPY src ./src
RUN npm run build

# Production image
FROM node:lts-alpine
WORKDIR /app
ENV NODE_ENV=production

# Copy production artifacts
COPY --from=build /app/dist ./dist
COPY package.json package-lock.json ./

# Install production dependencies
RUN npm ci --production --ignore-scripts

# Start the MCP server
CMD ["node", "dist/index.js"]